// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4kyD0kMH_T1jC6mNhWpuyjfkWrO0kZ1Y',
    appId: '1:34509632847:web:dcc98eac5ab27a0988813a',
    messagingSenderId: '34509632847',
    projectId: 'transmaa-customer',
    authDomain: 'transmaa-customer.firebaseapp.com',
    databaseURL: 'https://transmaa-customer-default-rtdb.firebaseio.com',
    storageBucket: 'transmaa-customer.appspot.com',
    measurementId: 'G-RT8DC4LL1G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCigDAYUtYTDEZc6DeaNmV-Uf5obWBoaNY',
    appId: '1:34509632847:android:aa8a161f976f17c988813a',
    messagingSenderId: '34509632847',
    projectId: 'transmaa-customer',
    databaseURL: 'https://transmaa-customer-default-rtdb.firebaseio.com',
    storageBucket: 'transmaa-customer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeH9JRFmuEsPZq3EwDo-KiXXpBK183aMo',
    appId: '1:34509632847:ios:24f958f1d1769e6788813a',
    messagingSenderId: '34509632847',
    projectId: 'transmaa-customer',
    databaseURL: 'https://transmaa-customer-default-rtdb.firebaseio.com',
    storageBucket: 'transmaa-customer.appspot.com',
    iosBundleId: 'com.example.drivers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeH9JRFmuEsPZq3EwDo-KiXXpBK183aMo',
    appId: '1:34509632847:ios:2e6a53a09bcf541f88813a',
    messagingSenderId: '34509632847',
    projectId: 'transmaa-customer',
    databaseURL: 'https://transmaa-customer-default-rtdb.firebaseio.com',
    storageBucket: 'transmaa-customer.appspot.com',
    iosBundleId: 'com.example.drivers.RunnerTests',
  );
}
